language: python

python:
  - '3.6'

services:
  - docker

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels dranew
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda install -c olcbioinformatics vsnp
  - docker pull gcr.io/deepvariant-docker/deepvariant:0.8.0

script:
  - python -m pytest tests/test_vsnp_vcf.py -s -vv --maxfail=1
  - python -m pytest tests/test_vsnp_tree.py -s -vv --maxfail=1 
