# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  azure-storage:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    machine: true
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Download DeepVariant docker image
          command: docker pull google/deepvariant:1.5.0
      - run:
          name: Setup Environment and Run Tests
          command: |
            sudo apt update
            sudo apt install -y wget coreutils curl gnupg
            wget -O Mambaforge.sh  "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
            bash Mambaforge.sh -b -p "${HOME}/conda"
            source "${HOME}/conda/etc/profile.d/conda.sh"
            source "${HOME}/conda/etc/profile.d/mamba.sh"
            conda config --set always_yes yes --set changeps1 no
            conda update -y conda
            conda install mamba 
            conda config --add channels conda-forge
            conda config --add channels olcbioinformatics
            mamba create -n cowsnphr -c olcbioinformatics cowsnphr==0.0.33
            conda activate cowsnphr
            python -m pytest tests/
workflows:
    build_and_test:
        jobs:
          - azure-storage:
              filters:
                branches:
                  ignore: gh-pages